# Generated by Django 4.1.7 on 2023-02-27 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(max_length=20, verbose_name='Centro de Custos')),
                ('name', models.CharField(max_length=25, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='HeadQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('address', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=120, verbose_name='E-mail de contato')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('birth', models.DateField(verbose_name='Data de nascimento')),
                ('admission', models.DateField(verbose_name='Data de Ingresso')),
                ('shutdown', models.DateField(verbose_name='Data de Desligamento')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.department')),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headquarters', to='core.headquarter')),
            ],
        ),
    ]
